# Generated by Django 5.0.1 on 2024-04-19 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cart_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DELIVERD', 'DELIVERD')], default='pending', max_length=100)),
                ('total_amount', models.IntegerField()),
                ('fname', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
